#26917: Magneto redirects handling - fix processing on the client side
BudsiesApp/vue-storefront pull request #107
Opened 2022-07-13 09:00 UTC by soarer1004

2022-07-13 22:03 UTC, gorbunovav requested changes

2022-07-13 22:03 UTC, gorbunovav commented on core/modules/url/helpers/index.ts
> +  const userRoute = userRouteByName || userRouteByPath;
@Anton Sylka если тут ожидается Route, то возможно поиск совпадающего пути лучше выполнять в функции fallback'а, чем передавать несуществующий name оттуда? 🤔

И еще у меня не работает редиеркт, если он установлен на страницу Storyblok (например, ссылка Affilates в футере - там в Magento сейчас есть редирект на Storyblok-страницу `/affiliate_home`).

2022-07-14 03:52 UTC, soarer1004 commented on core/modules/url/helpers/index.ts
> +  const userRoute = userRouteByName || userRouteByPath;
@gorbunovav Похоже что этого редиректа нет в ES, т.к. API 404 возвращает(Локально смотрел, сейчас со стэйджинг API проверю). Хотя тут даже если и найдется редирект, может быть в другом еще проблема

2022-07-14 05:40 UTC, soarer1004 commented on core/modules/url/helpers/index.ts
> +  const userRoute = userRouteByName || userRouteByPath;
@gorbunovav Тут получается из-за того что в редиректах могут быть ссылки на страницы Storyblok, мы не можем всегда найти имя маршрута в fallback'е. Как вариант можно:
* возвращать из fallback'a `targetPath`;
* в `mapFallbackUrl` (`theme/config/modules`) пытаться найти именованный маршрут, если `targetPath` не undefined;
* если нашли именованный маршрут - возвращаем его;
* если нет, то возвращаем fallback для Storyblok с `targetPath` в качестве `url`.

По количеству обращений к API будет тоже самое что и при SSR.

2022-07-14 17:16 UTC, gorbunovav requested changes

2022-07-14 17:16 UTC, gorbunovav commented on src/modules/url-rewrite/mappingFallback.ts
> +    return `/${targetPath}/`;
@soarer1004 а у нас же не зафиксировано жестко в каком там виде url придет. Лучше наверное добавлять слэши только при их отсутствии?

2022-07-14 17:16 UTC, gorbunovav commented on core/modules/url/helpers/index.ts
> +      : `${path.startsWith('/') ? '' : '/'}${path}`;
А эти изменения в связи с чем понадобились? Вроде как ты в любом случае route возвращаешь?
Или это для того, чтобы path поменялся при redirect?

2022-07-15 02:52 UTC, soarer1004 commented on src/modules/url-rewrite/mappingFallback.ts
> +    return `/${targetPath}/`;
@soarer1004 Там выше по коду регуляркой удаляются начальный слэш и в конце. В этом месте всегда слэши будут отсутствовать

2022-07-15 02:58 UTC, soarer1004 commented on core/modules/url/helpers/index.ts
> +      : `${path.startsWith('/') ? '' : '/'}${path}`;
@gorbunovav Да, чтобы url соответствовал маршруту. Например, чтобы при переходе на `/face-masks/`, url был  как у соответствующего маршрута - `/plushie/index/printedMasks/` вместо `/face-masks/`

2022-07-15 12:12 UTC, gorbunovav approved these changes

2022-07-15 12:12 UTC, merged