#29074: Fetch current promo campaign after getting cart token
BudsiesApp/vue-storefront pull request #154
Opened 2023-05-04 09:20 UTC by soarer1004

2023-05-04 16:14 UTC, gorbunovav requested changes

2023-05-04 16:14 UTC, gorbunovav commented on core/modules/cart/store/actions/connectActions.ts
> +      await dispatch('promotionPlatform/fetchActiveCampaign', {cartId: result, userToken}, {root: true});
а мы можем это сделать в модуле promotion-platform?

2023-05-05 03:30 UTC, soarer1004 commented on core/modules/cart/store/actions/connectActions.ts
> +      await dispatch('promotionPlatform/fetchActiveCampaign', {cartId: result, userToken}, {root: true});
@gorbunovav Думаю да. Нам же не нужно, по идее, дожидаться завершения запроса на получение активной кампании. Т.к. синхронизация корзины от этого не зависит

2023-05-05 12:36 UTC, gorbunovav commented on core/modules/cart/store/actions/connectActions.ts
> +      EventBus.$emit('cart-connected', {cartId: result, userToken});
@soarer1004 возможно логичнее событие в конце экшена кидать, когда он все свои действия уже выполнил?

2023-05-10 04:03 UTC, soarer1004 commented on core/modules/cart/store/actions/connectActions.ts
> +      EventBus.$emit('cart-connected', {cartId: result, userToken});
@gorbunovav Не уверен что имеет смысл ждать синхронизации айтемов в корзине. Ну и плюс в этом месте токен уже получен, т.е. корзина уже создана/смержена. Т.е. как раз уже `connected`

2023-05-10 04:06 UTC, soarer1004 commented on core/modules/cart/store/actions/connectActions.ts
> +      EventBus.$emit('cart-connected', {cartId: result, userToken});
Ну и код тогда менее лаконичный получается:
```js
let difflog;

if (shouldMergeCart && !isUserInCheckout) {
    difflog = await dispatch('pullServerCart');
} else {
    difflog = await dispatch('sync', { forceClientState, dryRun: !config.cart.serverMergeByDefault })
}

EventBus.$emit('cart-connected', {cartId: result, userToken});
return difflog;
```

2023-05-10 10:40 UTC, soarer1004 commented on core/modules/cart/store/actions/connectActions.ts
> +      EventBus.$emit('cart-connected', {cartId: result, userToken});
@gorbunovav Перенес в конец экшена

2023-05-10 12:38 UTC, gorbunovav approved these changes

2023-05-10 12:38 UTC, merged