Refs #24743: Promotion Platform - fix mutations
BudsiesApp/vue-storefront pull request #16
Opened 2021-10-20 10:53 UTC by soarer1004

2021-10-21 22:23 UTC, gorbunovav requested changes

2021-10-21 22:23 UTC, gorbunovav commented on src/modules/promotion-platform/store/getters.ts
> +      return Number.parseInt(discount.split('$')[1], 10);
Вообще логичнее бы было наоборот - хранить в виде обычного числа, а при необходимости форматировать.
Разве нет?

2021-10-25 10:28 UTC, gorbunovav requested changes

2021-10-25 10:28 UTC, gorbunovav commented on src/modules/promotion-platform/types/UpdateProductCampaignDiscountEvent.interface.ts
> +}
Смысл события в том, что ты его выбрасываешь в одном месте и ты не знаешь кто на него подписан и что с ним будет делать. Таким образом ты избавляешься от прямой зависимости со сторонними модулями.

Соответственно парметры события определяются местом его выбрасывания, а не местом использования.

У тебя здесь получается наоборот - ты создал событие под конкретное место использования, что ломает всю идею.

Интерфейс, описывающий параметры, соответственно должен находиться в том же модуле, где и выбрасывание события.

2021-10-25 10:28 UTC, gorbunovav commented on src/modules/promotion-platform/promotion-platform.service.ts
> +      }
я так понимаю у нас есть проблема с тем, что с сервера приходит строка? видимо нужно попросить возвращать число 🤔

2021-10-25 10:30 UTC, soarer1004 commented on src/modules/promotion-platform/promotion-platform.service.ts
> +      }
Да, с сервера строка приходит

2021-10-25 10:34 UTC, gorbunovav commented on src/modules/promotion-platform/promotion-platform.service.ts
> +      }
@soarer1004 мне кажется форматирование результата должно быть последним шагом и обратные преобразвания не стабильны и череваты ошибками. Соответственно лучше добиваться работы с данными в исходном формате 🤔

2021-11-02 12:21 UTC, gorbunovav approved these changes

2021-11-02 12:25 UTC, merged