#30336: Improve e commerce statistics
BudsiesApp/vue-storefront pull request #196
Opened 2023-09-15 07:51 UTC by soarer1004

2023-09-17 14:55 UTC, gorbunovav requested changes

2023-09-17 14:55 UTC, gorbunovav commented on src/modules/google-tag-manager/helpers/prepare-cart-item-data.function.ts
> +    price: getFinalPrice(price)
видимо можно добавить еще quantity (не знаю сюда или в base item; в спецификации для `add_to_cart`` это поле есть)

2023-09-17 14:55 UTC, gorbunovav commented on src/modules/google-tag-manager/helpers/EventBusListener.ts
> +      shareasale_sscid: getCookieByName(shareasaleSSCIDCookieName),
давай сгруппируем кастомные поля (не входящие в спецификацию GA) в поле `custom_fields`

2023-09-17 14:55 UTC, gorbunovav commented on src/modules/google-tag-manager/helpers/EventBusListener.ts
> +      shareasale_sscid: getCookieByName(shareasaleSSCIDCookieName),
добавь еще 
`subtotalValue: orderPaymentDetails.base_grand_total - orderPaymentDetails.base_shipping_amount - orderPaymentDetails.base_tax_amount`

(раньше `transactionValue` называлось)

2023-09-17 14:55 UTC, gorbunovav commented on src/modules/google-tag-manager/helpers/StoreMutationsListener.ts
> +      event: GoogleTagManagerEvents.VIEW_ITEM,
у меня этот эвент выбрасывается второй раз после добавления товара в корзину, например для Printed Socks.

Т.е. сначала трекается это событие когда заходишь на страницу продукта.
Потом жму добавить в корзину - трекается `add_to_cart` и после него уже появляется снова `view_item`. 
Возможно из за очистки продукта или из за страницы cross sells.

2023-09-17 14:55 UTC, gorbunovav commented on src/modules/google-tag-manager/helpers/StoreMutationsListener.ts
> +  private onCartAddMutationListener (payload: {product: CartItem}): void {
У нас как то по разному получилось - добавлеине в корзину через подписку на мутации в Vuex, а удаление - через подписку на хук.
Хук для добавления тоже вроде есть.

2023-09-17 14:55 UTC, gorbunovav commented on src/modules/google-tag-manager/helpers/EventBusListener.ts
> +      const finalPrice = price.special && price.special < price.regular
мы вроде везде функцию `getFinalPrice` используем, а почему тут по другому?

2023-09-18 09:19 UTC, soarer1004 commented on src/modules/google-tag-manager/helpers/StoreMutationsListener.ts
> +      event: GoogleTagManagerEvents.VIEW_ITEM,
Да, это из-за cross sells страницы происходило. Также заметил, что при гидрации после SSR это событие тоже не отправлялось т.к. мутация не вызывается. Сделал отдельное событие которое выбрасывается когда страница отобразилась

2023-09-20 07:55 UTC, gorbunovav approved these changes

2023-09-20 07:55 UTC, merged