24552 gift cards
BudsiesApp/vue-storefront pull request #20
Opened 2021-11-03 05:44 UTC by soarer1004

2021-11-09 17:54 UTC, gorbunovav requested changes

2021-11-09 17:54 UTC, gorbunovav commented on src/modules/gift-card/components/GiftCardTemplate.vue
> +    }
По идее все эти ручные рассчеты можно заменить на использование padding-top в процентах от ширины у контейнера - для задания нужного соотношения сторон и сохранения responsive-поведения.

2021-11-10 02:35 UTC, soarer1004 commented on src/modules/gift-card/components/GiftCardTemplate.vue
> +    }
@gorbunovav Да, я так изначально пробовал переделать. Там проблема тогда с размером шрифтов возникает

2021-11-10 02:35 UTC, soarer1004 commented on src/modules/gift-card/components/GiftCardTemplate.vue
> +    }
Поэтому впоследствии переделал обратно на `scale`

2021-11-10 08:47 UTC, gorbunovav commented on src/modules/gift-card/components/GiftCardTemplate.vue
> +    }
@soarer1004 ок

2021-11-10 08:48 UTC, gorbunovav commented on src/modules/gift-card/components/GiftCardTemplate.vue
> +    height: 402px;
@soarer1004 тут наверное тоже можно переменные тогда использовать? (чтобы брать значения из констант)

2021-11-10 10:00 UTC, soarer1004 commented on src/modules/gift-card/components/GiftCardTemplate.vue
> +    height: 402px;
@gorbunovav исправил

2021-11-10 10:34 UTC, merged