#25102: Fix price calculating for bundle products
BudsiesApp/vue-storefront pull request #21
Opened 2021-11-15 06:06 UTC by soarer1004

2021-11-15 15:56 UTC, gorbunovav commented on core/modules/catalog/helpers/associatedProducts/getProductLinkPrice.ts
> +      specialPrice: (product as any).special_price || (product as any).specialPrice,
А из за чего у нас названия полей в двух вариантах?
Там для original price нужно добавить видимо поля в интерфейс объекта.

И можно еще отдельно интерфейс объявить для оъекта с полями цен (субсет от `Product` получается) и использовать его для значения по умолчанию - тогда не нужно будет приведение к `any` использовать.

2021-11-15 15:59 UTC, gorbunovav requested changes

2021-11-15 15:59 UTC, gorbunovav commented on core/modules/catalog/helpers/bundleOptions.ts
> +  }).reduce((acc, val) => acc.concat(val), []);
попробуй может для всех этих `values`, `item`, `acc`, `val` задать чуть более конкретные имена - так сложно разбираться где есть что

2021-11-16 04:18 UTC, soarer1004 commented on core/modules/catalog/helpers/associatedProducts/getProductLinkPrice.ts
> +      specialPrice: (product as any).special_price || (product as any).specialPrice,
@gorbunovav названия в camelCase являются deprecated, как я понял. Типы поправил

2021-11-16 12:40 UTC, gorbunovav approved these changes

2021-11-16 12:40 UTC, merged