#30694: TrueVault - integrate javascript code and update links
BudsiesApp/vue-storefront pull request #210
Opened 2023-11-02 08:44 UTC by soarer1004

2023-11-02 13:49 UTC, gorbunovav commented on config/local.json.template
> -    "id": false
@soarer1004 а это на что влияет? просто во VueStorefront же есть модуль для Google Analytics, но мы по идее не хотим его инициализировать, т.к. мы его подключаем/взаимодействуем через Google Tag Manager.

2023-11-20 04:50 UTC, soarer1004 commented on config/local.json.template
> -    "id": false
@gorbunovav Тот модуль не используется нигде. Его по идее можно удалить вообще. Этот id передается в настройках для скрипта True Vault

2023-11-21 18:30 UTC, gorbunovav requested changes

2023-11-21 18:30 UTC, gorbunovav commented on src/modules/true-vault/helpers/privacy-policy.plugin.ts
> +})
@soarer1004 а для чего нам это оформлять в виде плагина? 
Это же просто значения из конфига - вроде к ним и так можно обратиться.
А так получается мы глобальное пространство засоряем.

2023-11-21 18:30 UTC, gorbunovav commented on src/modules/true-vault/helpers/register-components.function.ts
> +}
По идее же можно не регистрировать компоненты глобально а импортировать в местах использования.
Мне кажется это рекомендуемый подход, т.к. позволяет более четко отслеживать зависимости.

2023-11-22 05:48 UTC, gorbunovav commented on src/modules/true-vault/components/opt-out-link.vue
> +      :class="{'truevault-polaris-optout': isMounted}"
@soarer1004 а для чего нам тут ждать монтирования компонента?

2023-11-22 06:09 UTC, soarer1004 commented on src/modules/true-vault/components/opt-out-link.vue
> +      :class="{'truevault-polaris-optout': isMounted}"
@gorbunovav скрипт TrueVault этот элемент не скрывает через атрибут, а полностью удаляет. Из-за этого при гидрации получается предупреждение о несоответствии элементов

2023-12-11 10:37 UTC, gorbunovav approved these changes

2023-12-11 10:37 UTC, merged