#30502: Storyblok Pages - implement breadcrumbs
BudsiesApp/vue-storefront pull request #212
Opened 2023-11-10 09:35 UTC by soarer1004

2023-11-13 17:03 UTC, gorbunovav requested changes

2023-11-13 17:03 UTC, gorbunovav commented on src/modules/vsf-storyblok-module/helpers/resolve-parent-data.function.ts
> +    parent: resolveParentData(parentData.parent)
хорошо бы защиту от циклических ссылок добавить (в т.ч. с зацикливанием через несколько звеньев)

2023-11-13 17:03 UTC, gorbunovav commented on src/modules/vsf-storyblok-module/components/defaults/page/BreadcrumbItem.vue
> +      <page-breadcrumbs :data="data.parent" />
а для чего нам такая сложная рекурсия компонетов - разве нельзя в родительском компоненте просто пройтись по всей цепочке и вывести item'ы?

2023-11-13 17:03 UTC, gorbunovav commented on src/modules/vsf-storyblok-module/components/defaults/page/Breadcrumbs.vue
> +  },
а для чего нам тут inject делать - ты же вроде и все данные истории сюда передаешь?

2023-11-14 13:47 UTC, gorbunovav requested changes

2023-11-14 13:47 UTC, gorbunovav commented on src/modules/vsf-storyblok-module/components/defaults/PageBreadcrumbs.vue
> +export default (Vue as VueConstructor<Vue & InjectedServices>).extend({
Inject'а же больше нет

2023-11-14 13:47 UTC, gorbunovav commented on src/modules/vsf-storyblok-module/helpers/resolve-parent-data.factory.ts
> +    return resolve(parent);
Предлагаю избавиться все таки от рекурсии - тогда не нужно будет мудрить с многоуровневым объявлением функций. (и в API тоже)

Можно пройтись сначала засунуть родителей в массив, а потом в обратном порядке их доставать и обрабатывать.

Или, если оставлять рекурсию, то по идее можно же проще сделать - можно вызывать `resolve` прямо в основной функции - тогда снаружи это будет выглядеть просто как вызов обычной функции и внутри не надо с очисткой заморачиваться 🤔 (т.к. контекст после выполнения не будет сохраняться).

А как Storyblok кстати на циклические ссылки реагирует? Он жн вроде должен parent вложенно резолвить

2023-11-15 06:17 UTC, soarer1004 commented on src/modules/vsf-storyblok-module/helpers/resolve-parent-data.factory.ts
> +    return resolve(parent);
> А как Storyblok кстати на циклические ссылки реагирует?

Storyblok не резолвит такие истории, возвращает только `id` у истории, которая имеет циклическую ссылку. Учел этот момент в коде.

2023-11-15 06:20 UTC, soarer1004 commented on src/modules/vsf-storyblok-module/helpers/resolve-parent-data.factory.ts
> +    return resolve(parent);
Но при этом идущие до этого истории резолвит нормально. На практике так получается:
`story1` -> `story2` -> `story3` -> `story1` - зарезолвятся 1,2 и 3 . У 3 в поле `parent` будет `id` первой

2023-11-15 10:12 UTC, gorbunovav requested changes

2023-11-15 10:12 UTC, gorbunovav commented on src/modules/vsf-storyblok-module/helpers/resolve-parent-data.function.ts
> +    parents.push(parent);
```suggestion
        parents.push(parent);

        const nextParent = getStoryParent(parent);
```

2023-11-15 10:12 UTC, gorbunovav commented on src/modules/vsf-storyblok-module/helpers/resolve-parent-data.function.ts
> +  return parents[0];
```suggestion
  let previousParentData;
  let parentData;

  while (parents.length > 0) {
    const parent = parents.pop();

    parentData = {
      slug: parent.full_slug,
      name: parent.name,
      id: parent.id,
      parent: previousParentData
    };

    previousParentData = parentData;
  }

  return parentData;
```

2023-11-15 15:27 UTC, gorbunovav commented on src/modules/vsf-storyblok-module/components/global/Cms.vue
> +../../helpers/resolve-parent-data.function
@soarer1004 какие то артефакты, похоже

2023-11-21 14:46 UTC, gorbunovav approved these changes

2023-11-21 14:46 UTC, merged