25345-respect-promo-campaign
BudsiesApp/vue-storefront pull request #23
Opened 2021-11-16 09:53 UTC by d-kochnov-optimus

2021-11-23 18:11 UTC, gorbunovav requested changes

2021-11-23 18:11 UTC, gorbunovav commented on core/data-resolver/CartService.ts
> +  EventBus.$emit('before_execute_cart_create_task', eventData)
Тут видимо лучше передавать не url, а массив/объект с доп параметрами.
Чтобы в обработчике парсингом/генерацией url не заниматься.

2021-11-23 18:11 UTC, gorbunovav commented on src/modules/promotion-platform/helpers/initEventBusListeners.ts
> +  EventBus.$on('before_execute_cart_create_task', (data: { url: string }) => {
как то нотации разные для названий эвентов получаются (в первом случае дефис, а тут подчеркивание)

2021-11-23 18:11 UTC, gorbunovav commented on src/modules/promotion-platform/index.ts
> +    initModule()
т.е. получается у нас модуль инициализируеутся только при создании корзины? 🤔

и второй вопрос - это может происходить несколько раз?

2021-11-24 09:42 UTC, d-kochnov-optimus commented on src/modules/promotion-platform/index.ts
> +    initModule()
@gorbunovav 

Я бы сказал модуль инициализируется после инициализации корзины (мы же должны передать токен корзины, если он есть, в запросе текущей кампании, а токен корзины в store доступен только после ее инициализации).

Второй вопрос интересный.
Инициализация пустой корзины происходит один раз - после загрузки страницы (если корзина была, то событие не выкидывается). В процессе перехода по страницам повторно она не инициализируется.
Второй вариант инициализации у меня по мутации `CART_LOAD_CART_SERVER_TOKEN`. Она срабатывает после перезагрузки страницы с имеющейся корзиной и после восстановления корзины.
Сейчас посмотрел и увидел, что мутация срабатывает еще после добавления продукта в корзину и после перехода на страницу checkout (в этом случае корзина вообще фактически переинициализируется) - по идее это не правильно, нам же модуль нужно один раз только проинициализировать.

Предлагаю тогда так поправить:
Удалить инициализацию по мутации.
В экшене создания (инициализации) корзины бросать не `empty-cart-without-token-created` а `cart-created` событие без условия наличия токена корзины. 
В обработчике инициализировать модуль + добавить флаг что бы инициализировать его только один раз (т.к. событие будет срабатывать и при переходе на checkout). Так мы закроем кейсы с загрузкой страницы с пустой и не пустой корзиной.
В таком варианте остается кейс с восстановлением корзины - видимо проще добавть отдельное событие `after-cart-recovery` на странице восстановления корзины и по нему просто повторно загружать кампанию (токен корзины уже будет в store).

2021-11-24 10:47 UTC, gorbunovav commented on src/modules/promotion-platform/index.ts
> +    initModule()
@d-kochnov-optimus согласен, давай так сделаем

2021-11-24 14:43 UTC, gorbunovav requested changes

2021-11-24 14:43 UTC, gorbunovav commented on core/data-resolver/CartService.ts
> +  EventBus.$emit('before-execute-cart-create-task', parsedUrl)
Это не совсем то, что я имел ввиду - зачеми подписчику на событие вообще знать о существовании url? 
Можно же просто собрать дополнительные параметры, а тут уже решать каким образом их передавать на сервер.

2021-11-24 17:25 UTC, gorbunovav approved these changes

2021-11-24 17:43 UTC, merged