24553 giftcards payment
BudsiesApp/vue-storefront pull request #24
Opened 2021-11-17 11:22 UTC by soarer1004

2021-11-18 15:11 UTC, gorbunovav requested changes

2021-11-18 15:11 UTC, gorbunovav commented on src/modules/gift-card/helpers/get-hidden-code.function.ts
> +export default function getHiddenCode (code: string): string {
getMaskedCode

2021-11-18 15:11 UTC, gorbunovav commented on src/modules/gift-card/helpers/get-hidden-code.function.ts
> +  const hiddenChar = 'X';
maskChar

2021-11-18 15:11 UTC, gorbunovav commented on src/modules/gift-card/gift-card.service.ts
> +    // TODO check why request errors not throwing
возможно из за флага silent: true в параметрах задания?

2021-11-18 15:11 UTC, gorbunovav commented on src/modules/gift-card/mixins/AppliedGiftCard.ts
> +      this.isRemoving = false;
try - finally?

2021-11-18 15:11 UTC, gorbunovav commented on src/modules/gift-card/mixins/AppliedGiftCard.ts
> +    SfLoader
мне кажется раз эти компоненты внутри миксина никак не используются - то лучше их тут и не добавлять, т.к. это получается деталь реализации уже конкретного компонента и его шаблона.

2021-11-18 15:11 UTC, gorbunovav commented on src/modules/gift-card/mixins/Payment.ts
> +    }
я бы может сделал setter и там бы вызывал удаление существующих карт - мне кажется в setter'е более явно прослеживается намерение изменить текущее состояние и соответственно такое "тяжелое" действие, как изменение данных на сервере более ожидаемо 🤔

2021-11-18 15:11 UTC, gorbunovav commented on src/modules/gift-card/mixins/AppliedGiftCard.ts
> +      isRemoving: false
нужен видимо какой то общий флаг еще (calculated property?) потому что сейчас возможно одновременно отправить запрос на редактирование суммы и на удаление карты

2021-11-18 15:11 UTC, gorbunovav commented on src/modules/gift-card/helpers/get-hidden-code.function.ts
> +  let suffixCode = code.slice(prefixLength).replace(/([A-Z,0-9]{1})/g, hiddenChar);
возможно лушче заменять просто все, кроме знака дефис? 🤔

2021-11-18 15:11 UTC, gorbunovav commented on src/modules/gift-card/mixins/AppliedGiftCard.ts
> +      giftCardValueModel: 0,
наверное можно навзвать `newGiftCardValue` - т.к. это по сути поле для нового значения карты при ее редактировании 🤔

2021-11-18 15:11 UTC, gorbunovav commented on src/modules/gift-card/mixins/AppliedGiftCard.ts
> +      this.isAmountEditing = true;
мне кажется лучше сделать разные обработчики на переход в режим редактирование и на сабмит

2021-11-18 15:11 UTC, gorbunovav commented on src/modules/gift-card/mixins/AppliedGiftCard.ts
> +      isChangingValue: false,
isSubmittingNewValue ?

2021-11-19 03:24 UTC, soarer1004 commented on src/modules/gift-card/gift-card.service.ts
> +    // TODO check why request errors not throwing
Как я понимаю, этот параметр отвечает только за отображение всплывающего оповещения с ошибкой. При silent: false ошибка всё равно обрабатывается где-то раньше

2021-11-19 04:16 UTC, soarer1004 commented on src/modules/gift-card/helpers/get-hidden-code.function.ts
> +  let suffixCode = code.slice(prefixLength).replace(/([A-Z,0-9]{1})/g, hiddenChar);
У сертификатов же, получается, начало кода может быть одинаковое. Тогда пользователю будет сложно различить добавленные сертификаты

2021-11-19 11:47 UTC, gorbunovav approved these changes

2021-11-19 11:48 UTC, merged