#32268: Product Forms - add support for `showInUrlQuery` field
BudsiesApp/vue-storefront pull request #252
Opened 2024-06-20 09:26 UTC by soarer1004

2024-06-26 20:53 UTC, gorbunovav requested changes

2024-06-26 20:53 UTC, gorbunovav commented on src/modules/customization-system/composables/use-available-customizations.ts
> +    availableCustomization,
хм, а разница получается в том, что одно массив, а другое - хэш? 
Мне кажется не очевидно, добавь TODO плз чтобы переименовать как то более явно

2024-06-26 20:53 UTC, gorbunovav commented on src/modules/customization-system/composables/use-selected-option-value-url-query.ts
> +        dictionary[optionValue.sku] = optionValue;
а тут получается расчет на то, что sku у значения будет уникальным среди всех значений всех кастомизаций? 
мне кажется на это не стоит рассчитывать

2024-06-27 00:58 UTC, soarer1004 commented on src/modules/customization-system/composables/use-available-customizations.ts
> +    availableCustomization,
Да, добавил TODO

2024-06-27 09:59 UTC, gorbunovav approved these changes

2024-06-27 09:59 UTC, merged