#32335: Product Forms - add email widget support
BudsiesApp/vue-storefront pull request #256
Opened 2024-07-01 09:33 UTC by soarer1004

2024-07-03 14:10 UTC, gorbunovav requested changes

2024-07-03 14:10 UTC, gorbunovav commented on core/modules/cart/helpers/productChecksum.ts
> +  }
я немного переделал фильтрацию email customization - мне кажется так проще 🤔

2024-07-03 14:10 UTC, gorbunovav commented on src/modules/customization-system/types/option-type.ts
> +  CUSTOMER_EMAIL = 'customer_email',
и я добавил ей отдельный тип - чтобы проще было идентифицировать (widget по идее за отображение отвечает, а тут именно предназначение)

2024-07-03 14:10 UTC, gorbunovav commented on core/modules/cart/helpers/productChecksum.ts
> +  const emailCustomization = (product as any).customizations?.find(isEmailCustomization);
а почему у нас кстати в типах для CartItem/ServerItem есть `customizationState`, но нет `customizations`?

2024-07-04 02:41 UTC, soarer1004 commented on core/modules/cart/helpers/productChecksum.ts
> +  const emailCustomization = (product as any).customizations?.find(isEmailCustomization);
CartItem наследуется от `Product`, у него есть `customizations`. У `ServerItem` нет т.к. API их не возвращает в `cart/pull`/`cart/update`

2024-07-04 10:08 UTC, gorbunovav approved these changes

2024-07-04 10:08 UTC, merged