#24399: Add default store name support
BudsiesApp/vue-storefront pull request #27
Opened 2021-11-26 08:53 UTC by soarer1004

2021-11-26 13:49 UTC, gorbunovav commented on core/pages/Checkout.js
> +        additionalData: {
`additionalData` - слишком обобщенно, почему именно эти additional, а остальные - нет?

Лучше какие то более осмысленные названия использовать (`paymentDetauls` ?) и разбить на несколько групп при необходимости.

Плюс раз мы изменяем набор полей у Order - надо видимо интерфейс обновить.

2021-11-26 13:56 UTC, gorbunovav requested changes

2021-11-26 13:56 UTC, gorbunovav commented on config/local.json.petsies.example
> +  "defaultStoreName": "${DEFAULT_STORE_NAME}",
получается уже несколько параметров для магазина по умолчанию задаем - возможно логичнее тогда все же задавть в конфиге storeView и указывать просто defaultStoreCode? (там по моему и без включения multistore он пытается по коду найти storeView и достать оттуда другие параметры)

2021-11-26 13:56 UTC, gorbunovav commented on core/pages/Checkout.js
> +        additionalData: {
`additionalData` - слишком обобщенно, почему именно эти additional, а остальные - нет?

Лучше какие то более осмысленные названия использовать (`paymentDetauls` ?) и разбить на несколько групп при необходимости.

Плюс раз мы изменяем набор полей у Order - надо видимо интерфейс обновить.

2021-11-26 13:56 UTC, gorbunovav commented on src/modules/google-tag-manager/hooks/afterRegistration.ts
>          });
Я бы все же реализовал всю отправку данных в этом модуле.
Так будет удобнее отслеживать / настраивать наше взаимодействие с GTM.

В интересующих нас местах в компонентах можно выбрасывать собития или вызывать мутации, а тут на них подписаться и отправлять данные в GTM.

В текущем варианте код сильно размазан по компонентам - сложно отследить. 
А отправка данных в GTM/GA нас интересует как самостоятельная фича.

Комменты по отдельным компонентам смотри в PR по теме.

2021-12-03 06:58 UTC, soarer1004 commented on config/local.json.petsies.example
> +  "defaultStoreName": "${DEFAULT_STORE_NAME}",
Похоже, что все таки без включения multistore, defaultStoreCode не используется и в storeViews не ищется нужный store

2021-12-03 07:06 UTC, soarer1004 commented on config/local.json.petsies.example
> +  "defaultStoreName": "${DEFAULT_STORE_NAME}",
Хотя нет, должен использоваться. Разбираюсь почему не подтягивается правильный store

2021-12-03 11:45 UTC, gorbunovav requested changes

2021-12-03 11:45 UTC, gorbunovav commented on src/modules/google-tag-manager/helpers/EventBusListener.ts
> +    const event = CartEvents.CHECKOUT_SECTION_CHANGE;
(для всех обработчиков)

Я не думаю, что мы хотим увязывать внутренние коды событий с кодами в GTM.
Внутренние могут меняться по каким то своим соображениям, а в GTM мы скорее всего хотим чтобы они менялись как можно реже, т.к. там на них могут быть какие то пиксели и цепочки завязаны.

Т.е. я думаю это два разных набора констант должно быть.

2021-12-06 11:46 UTC, gorbunovav approved these changes

2021-12-06 11:46 UTC, merged