#33161: Product Price - update after promotional campaign content changed
BudsiesApp/vue-storefront pull request #305
Opened 2024-09-30 08:10 UTC by soarer1004

2025-04-07 15:50 UTC, gorbunovav requested changes

2025-04-07 15:50 UTC, gorbunovav commented on core/modules/cart/store/getters.ts
> +import { PROMOTION_PLATFORM_PRODUCT_DISCOUNT_GETTER } from 'src/modules/promotion-platform'
Так ты же получается добавил в `core` модули зависимости от наших модулей...

Связи между модулями должны представлять некую иерархию, где вышестоящие (более абстрактные) модули не должны зависеть от нижестоящих (более конкретных).

А также не должно быть двухсторонних связей (если модуль A зависит от модуля B, то модуль B не должен зависеть от A )

2025-04-07 15:50 UTC, gorbunovav commented on src/modules/google-tag-manager/helpers/EventBusListener.ts
> +              this.store.getters[GET_CART_ITEM_PRICE](cartItem)
а если внутрь store передавать (чтобы функция внутри уже сама получала цену)?

2025-04-07 15:50 UTC, gorbunovav commented on src/modules/promotion-platform/store/getters.ts
> +    return state.campaignContent?.productDiscountPriceDictionary || {};
it seems we need to update it after recent changes in the API response

2025-04-07 15:50 UTC, gorbunovav commented on core/modules/catalog/store/product/getters.ts
> +import { PROMOTION_PLATFORM_PRODUCT_DISCOUNT_GETTER } from 'src/modules/promotion-platform';
и тут тоже

2025-04-07 15:50 UTC, gorbunovav commented on core/modules/catalog/store/product/getters.ts
> +import { PROMOTION_PLATFORM_PRODUCT_DISCOUNT_GETTER } from 'src/modules/promotion-platform';
По идее надо в этом модуле в state словарь со скидками разместить, а promotion platform должен вносить в него данные

2025-04-07 15:50 UTC, gorbunovav commented on src/modules/vsf-storyblok-module/components/global/rich-text/components/TextComponent.vue
> +import { CAMPAIGN_CONTENT_CHANGED } from 'src/modules/promotion-platform';
По идее этому компоненту нет необходимости знать о promotion paltform - ему интересны конечные цены.

Наверное мы можем использовать для вывода цен компоненты, которым в качестве property будут передаваться ID продукта и вид цены.
А они внутри уже будут из Vuex получать цены.
Тогда по идее и событие не понадобится.

2025-04-07 15:50 UTC, gorbunovav commented on src/modules/shared/helpers/product-discount-price.ts
> +  return productDiscount[product.id];
Тут я что то не очень понимаю что к чему.

"productDiscount" - это вроде как "скидка на продукт".

Функция называется "getDiscountPrice" - имеется ввиду "getDiscountedPrice"/ "getPriceWithDiscount"? (цена со скидкой)
Если это цена - то почему вовзращается размер скидки?

2025-04-07 15:50 UTC, gorbunovav commented on core/modules/cart/store/getters.ts
> +  getCartItemPrice: (state, getters, rootState, rootGetters): (cartItem: CartItem) => PriceHelper.ProductPrice => {
а когда cart item с сервера загружается - там не получается, что скидка дважды применяется? (на сервере и на клиенте)

2025-04-07 15:50 UTC, gorbunovav commented on core/modules/cart/store/getters.ts
> +      const productDiscountPriceDictionary = rootGetters[PROMOTION_PLATFORM_PRODUCT_DISCOUNT_GETTER];
это видимо уже после проверки price можно делать

2025-04-10 06:04 UTC, soarer1004 commented on src/modules/shared/helpers/product-discount-price.ts
> +  return productDiscount[product.id];
Да, действительно. Это именно цена со скидкой. `productDiscount` тоже содержит цены со скидкой. Переименовал связанные функции и переменные

2025-04-10 06:08 UTC, soarer1004 commented on core/modules/cart/store/getters.ts
> +  getCartItemPrice: (state, getters, rootState, rootGetters): (cartItem: CartItem) => PriceHelper.ProductPrice => {
Нет, мы на данный момент рассчитываем цену для продуктов в корзине основываясь на ценах продукта(поле `cartItem.price` не используется в рассчетах). Мы вроде бы обсуждали что можно избавиться от рассчета цен продуктов в корзине и просто выводить `cartItem.price`. Но тогда нужно еще поле `cartItem.regularPrice` добавить в ответ `cart/pull` и `cart/update` чтобы можно было скидку отобразить

2025-04-11 10:40 UTC, merged