#24911: Rendering storyblok directives on the Frontend
BudsiesApp/vue-storefront pull request #31
Opened 2021-12-01 08:47 UTC by soarer1004

2021-12-01 13:16 UTC, gorbunovav requested changes

2021-12-01 13:16 UTC, gorbunovav commented on src/modules/vsf-storyblok-module/components/global/RichText.vue
> +    EventBus.$on('promotion-platform-store-synchronized', this.parseDirectivesInHtml);
получается вызов идет без параметрта?

2021-12-01 13:16 UTC, gorbunovav commented on src/modules/vsf-storyblok-module/components/global/RichText.vue
> +    parseDirectivesInHtml (html) {
лучше наверное назвать `processDirectivesInHtml` ("parse" - это обычно извлечение данных)

2021-12-01 13:16 UTC, gorbunovav commented on src/modules/vsf-storyblok-module/components/global/RichText.vue
> +      return { productPriceDirectives };
а зачем возвращать в виде объекта с одинм полем? 🤔

2021-12-01 13:16 UTC, gorbunovav commented on src/modules/vsf-storyblok-module/components/global/RichText.vue
> +      }
По идее можно перевернуть условие и по нему просто вставить блок с загрузкой продуктов - дальше код идет одинаковый для обоих кейсов.

2021-12-01 13:16 UTC, gorbunovav commented on src/modules/vsf-storyblok-module/components/global/RichText.vue
> +      });
Мне кажется лучше `for..of` использовать всегда если нет каких то явных причин для `forEach`.
И условие можно перевернуть, вставив просто `continue`.

2021-12-01 13:16 UTC, gorbunovav commented on src/modules/vsf-storyblok-module/components/global/RichText.vue
> +const directiveDataRegexp = /(.*)\((.*)\)/gi;
а для чего нам модификатор `g`, если мы рассчитываем на одно вхождение/один результат? 🤔

2021-12-01 13:16 UTC, gorbunovav commented on src/modules/vsf-storyblok-module/components/global/RichText.vue
> +        if (directiveName && directiveName === 'productPrice') {
вроде бы не может быть кейса когда directiveName отсутствует? (плюс даже если `undefined` - все равно же не равно строке будет?)

2021-12-01 13:16 UTC, gorbunovav commented on src/modules/vsf-storyblok-module/components/global/RichText.vue
> +    },
я бы наверное разделил ответственность - один метод лучше пусть отвечает за вычисление значений директив, а второй за замену в тексте.

2021-12-01 13:16 UTC, gorbunovav commented on src/modules/vsf-storyblok-module/components/global/RichText.vue
> +    this.parseDirectivesInHtml(this.html);
А по идее у нас при обработке на сервере два раза обработка происходит?🤔
Как вариант можно хранить обработанные текст где то в vuex с уникальным идентификатором блока.
Но это можно в отдельную задачу вынести 🤔

Еще в официальном гайде по SSR рекомендуют код для клиента класть не в `created`, а в `mounted` (как раз потому что он только на клиенте выполняется).

2021-12-01 14:51 UTC, gorbunovav commented on core/modules/catalog/store/product/actions.ts
> +    context.commit(types.PRODUCT_SET_PRODUCT_BY_SKU, product);
тут получается есть еще кейс, что продукт не найден 🤔

2021-12-02 03:02 UTC, soarer1004 commented on src/modules/vsf-storyblok-module/components/global/RichText.vue
> +      return { productPriceDirectives };
Думал, что есть еще другие директивы, которые нужно будет добавлять. С таким подходом будет проще их добавлять

2021-12-02 03:30 UTC, soarer1004 commented on src/modules/vsf-storyblok-module/components/global/RichText.vue
> +      });
@gorbunovav Переделал на `for...of`. Если директива только одна будет, то можно перевернуть условие. Если будут еще директивы, то переворачивать условие особо смысла нет, как мне кажется

2021-12-02 03:36 UTC, soarer1004 commented on src/modules/vsf-storyblok-module/components/global/RichText.vue
> +    this.parseDirectivesInHtml(this.html);
@gorbunovav При обработке на сервере да - один раз на сервере и затем на клиенте. Если в Vuex хранить, было бы тогда хорошо, чтобы сервер учитывал промо кампании. Иначе все равно придётся повторно на клиенте пересчитывать, если промо кампания будет применена. Тут код для клиента поместил в created хук, чтобы результат был рассчитан как можно раньше

2021-12-02 10:56 UTC, gorbunovav approved these changes

2021-12-02 10:56 UTC, merged