#24615: Improve current product reset
BudsiesApp/vue-storefront pull request #32
Opened 2021-12-07 08:25 UTC by soarer1004

2021-12-09 13:15 UTC, gorbunovav requested changes

2021-12-09 13:15 UTC, gorbunovav commented on core/modules/catalog/store/product/actions.ts
> +    await dispatch('loadProductData', { product, route });
Тут получается в этом методе кроме установки текущего продукта еще выбрасывается событие и устанавливаются cache tags. 

Получается в новой реалзиации на наших страницах эти действия больше не вызываются.
Это сделано специально?

Влияет ли на что то момент вызыва `setCurrent` внутри метода? Если нет, то можно, наверное, сделать один метод со всеми действиями, кроме `setCurrent`, а второй может вызывать первый и делать `setCurrent` в конце. Либо через флаг это как то организовать 🤔

2021-12-10 03:54 UTC, soarer1004 commented on core/modules/catalog/store/product/actions.ts
> +    await dispatch('loadProductData', { product, route });
Эти действия выполняются сейчас через вызов `product/loadProductData` в самих компонентах после загрузки продукта через `product/single`. Возможно лучше этот экшен все таки вызывать не сразу после загрузки продукта, а после того, как мы устанавливаем текущий продукт. Эти действия хоть и не используют `currentProduct`, но он используется в подписке на событие `product-after-load` в компоненте `m-related-products`. И, получается, если это событие выбрасывается до установки текущего продукта, то может логика компонента нарушиться

2021-12-10 10:32 UTC, gorbunovav commented on core/modules/catalog/store/product/actions.ts
> +    await dispatch('loadProductData', { product, route });
@soarer1004 что то я не вижу, чтобы в loadProductData выбрасывалось событие 'product-before-load' или вызывалась функция `setRequestCacheTags`. 

При этом ты заменил вызов `loadProduct` на `single` и `loadProductData` - т.е. как раз эти два момента выпадают из нового кода.

2021-12-10 10:50 UTC, gorbunovav commented on core/modules/catalog/store/product/actions.ts
> +    await dispatch('loadProductData', { product, route });
@soarer1004 опять же получается, что в новом коде `product-after-load` выбрасывается, а `product-before-load` - нет, что странно.

Подписок на эти события вроде нигде нет, кроме `m-related-products` - это файл в теме (возможно они есть в дефолтной теме).
При этом в событиях нет указания на то, какой продукт загружен - т.е. видимо предполагается, что он должен быть текущим в store🤔

Лучше видимо сделать, чтобы установку currentProduct можно было отключать при вызове (для сохранения совместимости со старым кодом) и  выбрасывать эти события только если продукт устанавливается.

Насчет `m-related-products` - его наверное можно переделать, чтобы он не использовал `currentProduct`, а получал его в property и новые продукты загружал при изменение значения (сохранение связанных продуктов в store там кстати сделано с указанием sku основного продукта, а не просто для current).

2021-12-13 03:47 UTC, soarer1004 commented on core/modules/catalog/store/product/actions.ts
> +    await dispatch('loadProductData', { product, route });
@gorbunovav Сделал отключение установки продукта в `loadProduct`. В `m-related-products`, если я правильно понял, в store сохраняются связанные продукты не через sku основого продукта, а с указанием типа(`crosssell`, `upsell`). Заменил подписку на событие `product-after-load` на watcher

2021-12-14 00:39 UTC, gorbunovav approved these changes

2021-12-14 00:40 UTC, merged