#33613: Search requests - avoid send OPTIONS requests
BudsiesApp/vue-storefront pull request #333
Opened 2024-12-11 07:08 UTC by soarer1004

2024-12-11 23:07 UTC, gorbunovav requested changes

2024-12-11 23:07 UTC, gorbunovav commented on core/lib/search/adapter/api-search-query/searchAdapter.ts
> +    if (isPostQueryMethod) {
в теории еще могут быть PUT и PATCH запросы или нет?

2024-12-11 23:07 UTC, gorbunovav commented on core/lib/search/adapter/api-search-query/searchAdapter.ts
> -    EventBus.$emit(BEFORE_STORE_BACKEND_API_REQUEST, payload);
Ты получается полностью выпилил указание версии приложения и идентификатора инстанса в запросах - но мне кажется это может быть полезным при дебаге.
Насколько сложно перенести эти параметры в query params?

2024-12-12 05:27 UTC, soarer1004 commented on core/lib/search/adapter/api-search-query/searchAdapter.ts
> +    if (isPostQueryMethod) {
Не уверен - это же запрос для поиска в ElasticSearch. Не думаю что здесь можно использовать методы для изменения состояния

2024-12-13 12:18 UTC, gorbunovav commented on core/data-resolver/UserService.ts
> +      }
@soarer1004 а это в связи с чем изменение? и там выше еще один GET-запрос - там тогда тоже имеет смысл добавить?

2024-12-13 12:25 UTC, merged

2024-12-16 04:26 UTC, soarer1004 commented on core/data-resolver/UserService.ts
> +      }
@gorbunovav Избавился от `content-type` заголовка для этого запроса. Да, запрос выше пропустил, похоже - исправил