24543: Implement Affirm Storyblok blocks with offers
BudsiesApp/vue-storefront pull request #51
Opened 2022-01-20 09:09 UTC by fand0rin

2022-01-21 09:40 UTC, gorbunovav commented on src/modules/payment-affirm/components/storyblok/AffirmMonthlyPayment.vue
> +          skipCache: true
@fand0rin а почему skipCache? 🤔

2022-01-21 09:48 UTC, gorbunovav requested changes

2022-01-21 09:48 UTC, gorbunovav commented on src/modules/payment-affirm/components/storyblok/AffirmMonthlyPayment.vue
> +    }
А это что за кейс? 🤔

Можно наверное watcher'ом ограничиться, сделать его только immediate.

Еще по идее возможен кейс, когда продукт в itemData не заполнен - когда блок только добавили во время редактирования и еще не успели указать значения.

2022-01-21 15:02 UTC, fand0rin commented on src/modules/payment-affirm/components/storyblok/AffirmMonthlyPayment.vue
> +    }
Там же в блоке product required, без указанного продукта нельзя сохранить

2022-01-24 09:07 UTC, gorbunovav approved these changes

2022-01-24 09:07 UTC, merged