#26183: Sync backend settings
BudsiesApp/vue-storefront pull request #81
Opened 2022-04-22 10:57 UTC by soarer1004

2022-04-25 20:52 UTC, gorbunovav requested changes

2022-04-25 20:52 UTC, gorbunovav commented on src/modules/backend-settings/store/getters.ts
> +        result = result[key];
@soarer1004 а что будет, если ключ первого уровня не существует?

2022-04-26 03:36 UTC, soarer1004 commented on src/modules/backend-settings/store/getters.ts
> +        result = result[key];
@gorbunovav Извиняюсь, не учел этот момент, исправил

2022-04-26 12:34 UTC, gorbunovav approved these changes

2022-04-26 12:34 UTC, merged