#26643: Rich Text - implement render with Vue components instead of v-html
BudsiesApp/vue-storefront pull request #97
Opened 2022-06-22 09:58 UTC by soarer1004

2022-06-23 16:50 UTC, gorbunovav requested changes

2022-06-23 16:50 UTC, gorbunovav commented on src/modules/vsf-storyblok-module/components/global/rich-text/RichText.vue
> +  <div class="test">
забыл убрать?

2022-06-23 16:50 UTC, gorbunovav commented on src/modules/vsf-storyblok-module/components/global/rich-text/RichText.vue
> +    }),
вроде бы этот getter не используется 🤔

2022-06-23 16:50 UTC, gorbunovav commented on src/modules/vsf-storyblok-module/components/global/rich-text/components/BaseElement.vue
> +<template>
давай назовем этот компонент `GenericComopnent`

2022-06-23 16:50 UTC, gorbunovav commented on src/modules/vsf-storyblok-module/components/global/rich-text/components/Text.vue
>  <template>
а этот `TextComponent`

2022-06-23 16:50 UTC, gorbunovav commented on src/modules/vsf-storyblok-module/components/global/rich-text/components/BaseElement.vue
> +    :is="rootElement"
предлагаю переименовать в `rootTagName`

2022-06-23 16:50 UTC, gorbunovav commented on src/modules/vsf-storyblok-module/helpers/get-rich-text-item-data.function.ts
> +        content: data.content,
Как думаешь - а мы можем тут проверить является ли элемент ссылкой и если да, то преобразовать его в компонент-ссылку и под-компонент текст? (чтобы сделать отдельный компонент "ссылка" и не смешивать их с текстом)

2022-06-24 03:06 UTC, soarer1004 commented on src/modules/vsf-storyblok-module/helpers/get-rich-text-item-data.function.ts
> +        content: data.content,
Похоже что в этом случае даже не нужен отдельный компонент-ссылка, можно использовать `RouterLink`, который уже есть в модуле

2022-06-24 13:57 UTC, gorbunovav approved these changes

2022-06-24 13:57 UTC, merged